version: "2.0"
services:

  mysql-master:
    image: mysql:5.7
    ports: 
      - "13306:3306"
    volumes:
      - ./conf/mysql-master:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
  mysql-slave1:
    image: mysql:5.7
    ports: 
      - "13307:3306"
    volumes:
      - ./conf/mysql-slave1:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
  mysql-slave2:
    image: mysql:5.7
    ports: 
      - "13308:3306"
    volumes:
      - ./conf/mysql-slave2:/etc/mysql/conf.d
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root

  proxysql:
    image: pondix/proxysql:latest-stretch
    ports:
      - "16033:6033"
      - "16032:6032"
    volumes:
      - ./conf/proxysql/proxysql.cnf:/etc/proxysql.cnf
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

